version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_weather
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db

  weather-backend:
    image: weather-backend
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - mongodb

volumes:
  mongodb_data:
